### ISSUE TITLE
code to view lines RDD entries throws error

### ISSUE THREAD

**Issue by chrised209** [learn-co-curriculum/dsc-word-count-with-map-reduce-lab#1]
The cells: 

print(lines.collect()[500])
print(lines.collect()[1000])

and:

lines.collect()for line in lines.collect():
    print(line)

both throw errors with similar traceback (error text at bottom of post).  The rdd methods from the previous lab (collect, take, first) all respond simiarly.  The behavior of RDDs made from the sc.textfile command seem to differ from those made from the sc.parallelize command.

Error Text:

Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-b127e3a7f812> in <module>
----> 1 print(lines.collect()[500])
      2 print(lines.collect()[1000])

/usr/local/spark/python/pyspark/rdd.py in collect(self)
    887         """
    888         with SCCallSiteSync(self.context) as css:
--> 889             sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
    890         return list(_load_from_socket(sock_info, self._jrdd_deserializer))
    891 

/usr/local/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/local/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/home/jovyan/work/text/hamlet.txt
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:297)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:239)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:325)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:205)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:276)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:272)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2179)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1004)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:388)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1003)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:168)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by chrised209** [comment]
The problem seemed to be that the /work folder had no /text/hamlet.txt.  Why the error isn't thrown when i attempt to create the RDD i don't know.  I got moving again by finding hamlet.txt at: 

https://gist.github.com/provpup/2fc41686eab7400b796b

, saving it to my Windows 10 machine's Documents folder.  Then i used the CLI from the Containers / Apps view in Docker to create the /text folder and then ran this command from PowerShell:

docker cp C:/Users/[username]/Documents/hamlet.txt adoring_lichterman:/home/jovyan/work/text/  

Once I reran the previous cell to create the RDD, I had some results.  Note that this version of hamlet.txt seems to give somewhat different results for specific line indices (off by about three lines).

I still recommend rewriting the instructions to smooth this out.  i'd rather focus on Spark than the finer points of Docker manipulation.

**Comment by hoffm386** [comment]
Hi Chris, I am not able to reproduce this error

My suggestion to anyone encountering a `org.apache.hadoop.mapred.InvalidInputException: Input path does not exist` error in the future is to try restarting the kernel and making sure that these base Python lines work before proceeding:

```python
import os
os.getcwd()
```

This code should print out the current working directory. If it gives you a `FileNotFoundError` instead, that means there is some problem with Python's ability to connect to the file system, and you should try restarting the kernel
